In [1]:
qual_file = '/Users/jnaiman/LMM_Figure_Parsing/resources/qualitative_coding/qualitative.csv'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(qual_file)

In [4]:
df

,Figure Name,Correct Number of Panels,Plotting Style Mentioned,Correct Number of Lines/Bars (NM=not mentioned),Correct plot type,Linestyles correct,y-axis tick labels correct,x-axis tick labels correct,x-axis label mentioned,"y-axis label mentioned (M=mentioned, C=correct, NC=not correct)","Title mentioned/Title correct (M=mentioned, C=correct, NC=not correct)",color bar mentioned,error bars mentioned (NA means no error bars),other hallucinations
0,Picture100,Y,N,Y/NA/N,Y/N/Y,N/NA/NA,N/N/N,N/N/N,N/N/N,N/N/N,NA/M-NC/M-C,NA/N/NA,NA/N/NA,0.0/1/1
1,Picture103,Y,N,N,Y,NaN,Y,Y,Y,M-NC,M-C,NaN,N,2
2,Picture104,Y,N,Y,Y,NaN,Y,Y,Y,M-NC,NaN,NaN,Y,0
3,Picture112,Y,N,NM,Y,NaN,Y,Y,Y,Y,Y,NaN,N,0
4,Picture117,Y,N,NA/NA/NA/NA,Y/Y/N/Y,NA/NA/NA/NA,Y/N/N/N,N/N/N/N,Y/Y/N/N,M-NC/M-NC/N/N,NA/Y/NA/NA,NA/M-NC/N/N,N/N/NA/N,1.0/1/0/1
5,Picture12,Y,N,NA/NM,Y/Y,NA/NA,N/N,N/N,N/N,NM/NM,M-NC/NA,NA/NA,NA/N,2.0/2.0
6,Picture139,Y,N,NM,Y,NaN,Y,Y,Y,NM,M-C,NaN,N,1

In [47]:
qual = {
    'Correct Number of Panels':{'incorrect':0, 'correct':0, 'df label':"Correct Number of Panels"},
    'Correct Plot Type':{'incorrect':0, 'correct':0, 'df label':"Correct plot type"},
    'Correct Number of Lines/Bars':{'incorrect':0, 'correct':0, 'df label':"Correct Number of Lines/Bars (NM=not mentioned)"},
    'Correct title':{'incorrect':0, 'correct':0, 'df label':"Title mentioned/Title correct (M=mentioned, C=correct, NC=not correct)"},
    'Correct x-axis labels':{'incorrect':0, 'correct':0, 'df label':"x-axis label mentioned"},
    'Correct y-axis labels':{'incorrect':0, 'correct':0, 'df label':"y-axis label mentioned (M=mentioned, C=correct, NC=not correct)"},
    'Correct x-axis tick labels':{'incorrect':0, 'correct':0, 'df label':"x-axis tick labels correct"},
    'Correct y-axis tick labels':{'incorrect':0, 'correct':0, 'df label':"y-axis tick labels correct"},
    'Error bars mentioned (when present)':{'incorrect':0, 'correct':0, 'df label':"error bars mentioned (NA means no error bars)"},
       }

for k,v in qual.items():
    d = df[v['df label']].values
    for dd in d: # all values
        if '/' not in str(dd):
            if str(dd).strip()=='Y':
                v['correct'] += 1
            elif str(dd).strip()=='N':
                v['incorrect'] += 1
            elif str(dd).strip()=='NM': # not mentioned
                v['incorrect'] += 1
            elif str(dd).strip()=='M-NC': # mentioned, but not correct
                v['incorrect'] += 1
            elif str(dd).strip()=='M-C': # mentioned, and correct
                v['correct'] += 1
            else:
                print('other:', str(dd).strip())
        else: # has multi
            d2 = dd.split('/')
            for dd2 in d2:
                if str(dd2).strip()=='Y':
                    v['correct'] += 1
                elif str(dd2).strip()=='N':
                    v['incorrect'] += 1
                elif str(dd2).strip()=='NM': # not mentioned
                    v['incorrect'] += 1
                elif str(dd2).strip()=='M-NC': # mentioned but not correct
                    v['incorrect'] += 1
                elif str(dd2).strip()=='M-C': # mentioned and correct
                    v['correct'] += 1
                else:
                    print('other, 2:', str(dd2).strip())
                
    #import sys; sys.exit()

other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other: nan
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA

In [48]:
qual_per = {} # percent correct
for k,v in qual.items():
    qual_per[k] = v['correct']/(v['correct']+v['incorrect'])*100

In [49]:
qual_per

{'Correct Number of Panels': 100.0,
 'Correct Plot Type': 84.61538461538461,
 'Correct Number of Lines/Bars': 28.57142857142857,
 'Correct title': 71.42857142857143,
 'Correct x-axis labels': 46.15384615384615,
 'Correct y-axis labels': 7.6923076923076925,
 'Correct x-axis tick labels': 30.76923076923077,
 'Correct y-axis tick labels': 38.46153846153847,
 'Error bars mentioned (when present)': 11.11111111111111}

Also count hallucinations:

In [29]:
hallucinations = 0
#hall_per_page = []
for d in df['other hallucinations'].values:
    if '/' not in d:
        hallucinations += int(float(d))
    else:
        dd = d.split('/')
        for d2 in dd:
            hallucinations += int(float(d2))

print('Total number of hallucinations:', hallucinations)

Total number of hallucinations: 12