In [77]:
qual_file = '/Users/jnaiman/LMM_Figure_Parsing/resources/qualitative_coding/qualitative_copilot.csv'

qual_file_gpt = '/Users/jnaiman/LMM_Figure_Parsing/resources/qualitative_coding/qualitative_chatgpt.csv'

In [69]:
import pandas as pd

## Copilot

In [70]:
df = pd.read_csv(qual_file)

In [71]:
df

,Figure Name,Correct Number of Panels,Plotting Style Mentioned,Correct Number of Lines/Bars (NM=not mentioned),Correct plot type,Linestyles correct,y-axis tick labels correct,x-axis tick labels correct,x-axis label mentioned,"y-axis label mentioned (M=mentioned, C=correct, NC=not correct)","Title mentioned/Title correct (M=mentioned, C=correct, NC=not correct)",color bar mentioned,error bars mentioned (NA means no error bars),other hallucinations
0,Picture100,Y,N,Y/NA/N,Y/N/Y,N/NA/NA,N/N/N,N/N/N,N/N/N,N/N/N,NA/M-NC/M-C,NA/N/NA,NA/N/NA,0.0/1/1
1,Picture103,Y,N,N,Y,NaN,Y,Y,Y,M-NC,M-C,NaN,N,2
2,Picture104,Y,N,Y,Y,NaN,Y,Y,Y,M-NC,NaN,NaN,Y,0
3,Picture112,Y,N,NM,Y,NaN,Y,Y,Y,Y,Y,NaN,N,0
4,Picture117,Y,N,NA/NA/NA/NA,Y/Y/N/Y,NA/NA/NA/NA,Y/N/N/N,N/N/N/N,Y/Y/N/N,M-NC/M-NC/N/N,NA/Y/NA/NA,NA/M-NC/N/N,N/N/NA/N,1.0/1/0/1
5,Picture12,Y,N,NA/NM,Y/Y,NA/NA,N/N,N/N,N/N,NM/NM,M-NC/NA,NA/NA,NA/N,2.0/2.0
6,Picture139,Y,N,NM,Y,NaN,Y,Y,Y,NM,M-C,NaN,N,1
7,Picture15,Y,N,NM,Y,NaN,Y,Y,N,M-C,NaN,NaN,N,1
8,Picture159,Y,N,NM,N,NaN,Y,Y,N,M-C,NaN,N,N,3
9,Picture16,Y,N,Y,Y,N,Y,Y,M-NC,M-C,NaN,NaN,NaN,2

In [72]:
qual = {
    'Correct Number of Panels':{'incorrect':0, 'correct':0, 'df label':"Correct Number of Panels"},
    'Correct Plot Type':{'incorrect':0, 'correct':0, 'df label':"Correct plot type"},
    'Correct Number of Lines/Bars':{'incorrect':0, 'correct':0, 'df label':"Correct Number of Lines/Bars (NM=not mentioned)"},
    'Correct title':{'incorrect':0, 'correct':0, 'df label':"Title mentioned/Title correct (M=mentioned, C=correct, NC=not correct)"},
    'Correct x-axis labels':{'incorrect':0, 'correct':0, 'df label':"x-axis label mentioned"},
    'Correct y-axis labels':{'incorrect':0, 'correct':0, 'df label':"y-axis label mentioned (M=mentioned, C=correct, NC=not correct)"},
    'Correct x-axis tick labels':{'incorrect':0, 'correct':0, 'df label':"x-axis tick labels correct"},
    'Correct y-axis tick labels':{'incorrect':0, 'correct':0, 'df label':"y-axis tick labels correct"},
    'Error bars mentioned (when present)':{'incorrect':0, 'correct':0, 'df label':"error bars mentioned (NA means no error bars)"},
       }

for k,v in qual.items():
    d = df[v['df label']].values
    for dd in d: # all values
        if '/' not in str(dd):
            if str(dd).strip()=='Y':
                v['correct'] += 1
            elif str(dd).strip()=='N':
                v['incorrect'] += 1
            elif str(dd).strip()=='NM': # not mentioned
                v['incorrect'] += 1
            elif str(dd).strip()=='M-NC': # mentioned, but not correct
                v['incorrect'] += 1
            elif str(dd).strip()=='M-C': # mentioned, and correct
                v['correct'] += 1
            else:
                print('other:', str(dd).strip())
        else: # has multi
            d2 = dd.split('/')
            for dd2 in d2:
                if str(dd2).strip()=='Y':
                    v['correct'] += 1
                elif str(dd2).strip()=='N':
                    v['incorrect'] += 1
                elif str(dd2).strip()=='NM': # not mentioned
                    v['incorrect'] += 1
                elif str(dd2).strip()=='M-NC': # mentioned but not correct
                    v['incorrect'] += 1
                elif str(dd2).strip()=='M-C': # mentioned and correct
                    v['correct'] += 1
                else:
                    print('other, 2:', str(dd2).strip())
                
    #import sys; sys.exit()

other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other: nan
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other: nan
other: nan
other: nan
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other: nan

In [73]:
qual_per = {} # percent correct
for k,v in qual.items():
    qual_per[k] = v['correct']/(v['correct']+v['incorrect'])*100

In [74]:
qual_per

{'Correct Number of Panels': 100.0,
 'Correct Plot Type': 81.25,
 'Correct Number of Lines/Bars': 30.0,
 'Correct title': 71.42857142857143,
 'Correct x-axis labels': 37.5,
 'Correct y-axis labels': 25.0,
 'Correct x-axis tick labels': 43.75,
 'Correct y-axis tick labels': 50.0,
 'Error bars mentioned (when present)': 9.090909090909092}

Count hallucinations:

In [79]:
hallucinations = 0
#hall_per_page = []
for d in df['other hallucinations'].values:
    if '/' not in d:
        hallucinations += int(float(d))
    else:
        dd = d.split('/')
        for d2 in dd:
            hallucinations += int(float(d2))

print('Total number of hallucinations:', hallucinations)

Total number of hallucinations: 18

## ChatGPT

In [78]:
df_gpt = pd.read_csv(qual_file_gpt)

In [80]:
df_gpt

,Figure Name,Correct Number of Panels,Plotting Style Mentioned,Correct Number of Lines/Bars (NM=not mentioned),Correct plot type,Linestyles correct,x-axis tick labels correct,y-axis tick labels correct,x-axis label mentioned,"y-axis label mentioned (M=mentioned, C=correct, NC=not correct)","Title mentioned/Title correct (M=mentioned, C=correct, NC=not correct)",color bar mentioned,error bars mentioned (NA means no error bars),other hallucinations
0,Picture100,Y,N,N/NA/NM,Y/N/Y,Y/NA/NA,N/Y/Y,Y/Y/Y,Y/N/N,M-NC/M-NC/M-NC,NA/Y/Y,NA/Y/NA,NA/N/Y,1.0/1.0/0.0
1,Picture103,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,0
2,Picture104,Y,N,N,Y,NaN,N,Y,Y,Y,NaN,NaN,Y,2
3,Picture112,Y,N,NM,Y,NaN,Y,Y,Y,Y,Y,NaN,N,0
4,Picture117,Y,N,NM/NA/NA/NA,Y/Y/Y/Y,NA/NA/NA/NA,Y/N/N/Y,Y/Y/Y/Y,Y/Y/Y/Y,Y/N/Y/Y,NA/N/NA/NA,NA/Y/Y/Y,N/N/NA/N,2.0/0/0/0
5,Picture12,Y,N,NA/NM,Y/Y,NA/NA,Y/Y,Y/Y,Y/Y,Y/Y,Y/N,NA/NA,NA/Y,1.0/1.0
6,Picture139,Y,N,NM,Y,NaN,Y,Y,Y,Y,Y,NaN,N,1
7,Picture15,Y,N,NM,Y,NaN,N,Y,N,Y,NaN,NaN,N,0
8,Picture159,Y,N,NaN,Y,NaN,Y,Y,M-NC,Y,NaN,Y,N,1
9,Picture16,Y,N,Y,Y,N,Y,NM,Y,Y,NaN,NaN,NaN,2

In [84]:
qual_gpt = {
    'Correct Number of Panels':{'incorrect':0, 'correct':0, 'df label':"Correct Number of Panels"},
    'Correct Plot Type':{'incorrect':0, 'correct':0, 'df label':"Correct plot type"},
    'Correct Number of Lines/Bars':{'incorrect':0, 'correct':0, 'df label':"Correct Number of Lines/Bars (NM=not mentioned)"},
    'Correct title':{'incorrect':0, 'correct':0, 'df label':"Title mentioned/Title correct (M=mentioned, C=correct, NC=not correct)"},
    'Correct x-axis labels':{'incorrect':0, 'correct':0, 'df label':"x-axis label mentioned"},
    'Correct y-axis labels':{'incorrect':0, 'correct':0, 'df label':"y-axis label mentioned (M=mentioned, C=correct, NC=not correct)"},
    'Correct x-axis tick labels':{'incorrect':0, 'correct':0, 'df label':"x-axis tick labels correct"},
    'Correct y-axis tick labels':{'incorrect':0, 'correct':0, 'df label':"y-axis tick labels correct"},
    'Error bars mentioned (when present)':{'incorrect':0, 'correct':0, 'df label':"error bars mentioned (NA means no error bars)"},
       }

for k,v in qual_gpt.items():
    d = df_gpt[v['df label']].values
    for dd in d: # all values
        if '/' not in str(dd):
            if str(dd).strip()=='Y':
                v['correct'] += 1
            elif str(dd).strip()=='N':
                v['incorrect'] += 1
            elif str(dd).strip()=='NM': # not mentioned
                v['incorrect'] += 1
            elif str(dd).strip()=='M-NC': # mentioned, but not correct
                v['incorrect'] += 1
            elif str(dd).strip()=='M-C': # mentioned, and correct
                v['correct'] += 1
            else:
                print('other:', str(dd).strip())
        else: # has multi
            d2 = dd.split('/')
            for dd2 in d2:
                if str(dd2).strip()=='Y':
                    v['correct'] += 1
                elif str(dd2).strip()=='N':
                    v['incorrect'] += 1
                elif str(dd2).strip()=='NM': # not mentioned
                    v['incorrect'] += 1
                elif str(dd2).strip()=='M-NC': # mentioned but not correct
                    v['incorrect'] += 1
                elif str(dd2).strip()=='M-C': # mentioned and correct
                    v['correct'] += 1
                else:
                    print('other, 2:', str(dd2).strip())
                
    #import sys; sys.exit()

other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other, 2: NA
other: nan
other, 2: NA
other: nan
other, 2: NA
other, 2: NA
other, 2: NA
other: nan
other: nan
other: nan
other, 2: NA
other, 2: NA
other, 2: NA
other: nan

In [85]:
qual_per_gpt = {} # percent correct
for k,v in qual_gpt.items():
    qual_per_gpt[k] = v['correct']/(v['correct']+v['incorrect'])*100

In [86]:
qual_per_gpt

{'Correct Number of Panels': 100.0,
 'Correct Plot Type': 93.75,
 'Correct Number of Lines/Bars': 20.0,
 'Correct title': 75.0,
 'Correct x-axis labels': 75.0,
 'Correct y-axis labels': 75.0,
 'Correct x-axis tick labels': 68.75,
 'Correct y-axis tick labels': 93.75,
 'Error bars mentioned (when present)': 33.33333333333333}

Count hallucinations:

In [87]:
hallucinations_gpt = 0
#hall_per_page = []
for d in df_gpt['other hallucinations'].values:
    if '/' not in d:
        hallucinations_gpt += int(float(d))
    else:
        dd = d.split('/')
        for d2 in dd:
            hallucinations_gpt += int(float(d2))

print('Total number of hallucinations:', hallucinations_gpt)

Total number of hallucinations: 12

## Output

format for paper:

In [90]:
for k,v in qual_per.items():
    print(k, '&', round(v), '&', round(qual_per_gpt[k]),' \\\\')

Correct Number of Panels & 100 & 100  \\
Correct Plot Type & 81 & 94  \\
Correct Number of Lines/Bars & 30 & 20  \\
Correct title & 71 & 75  \\
Correct x-axis labels & 38 & 75  \\
Correct y-axis labels & 25 & 75  \\
Correct x-axis tick labels & 44 & 69  \\
Correct y-axis tick labels & 50 & 94  \\
Error bars mentioned (when present) & 9 & 33  \\